version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: mysql_db
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Root@123
      MYSQL_DATABASE: cms_db
      MYSQL_USER: cms
      MYSQL_PASSWORD: cms_user@123
    ports:
      - "3301:3306"

  django:
    build: ./cms_app
    container_name: cms_app
    volumes:
      - ./cms_app:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - mailserver
    environment:
      DB_NAME: cms_db
      DB_USER: cms
      DB_PASSWORD: cms_user@123
      DB_HOST: db
      EMAIL_HOST: mailserver
      EMAIL_PORT: 1025

  mailserver:
    image: mailhog/mailhog
    container_name: mailserver
    ports:
      - "1025:1025"
      - "8025:8025"

networks:
  default:
    driver: bridge
