services:
  db:
    image: mysql:8
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: Root@123
      MYSQL_DATABASE: cms_db
      MYSQL_USER: cms
      MYSQL_PASSWORD: cms_user@123
    ports:
      - "3306:3306"
  app:
    build: .
    container_name: cms_app
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - mailserver
    environment:
      DB_NAME: cms_db
      DB_USER: cms
      DB_PASSWORD: cms_user@123
      DB_HOST: db
      EMAIL_HOST: mailserver
      EMAIL_PORT: 1025
  mailserver:
    image: mailhog/mailhog
    container_name: mailserver
    ports:
      - "1025:1025"
      - "8025:8025"

networks:
  default:
    driver: bridge
